### ISSUE TITLE
 error.type.InvalidOperationException: No merging service configuration.

### ISSUE THREAD

**Issue by brianraila** [santedb/hello-mpi#3]
I keep getting this error on the Matches Tab.

(InvalidOperationException) : {"$type":"InvalidOperationException","message":"No merging service configuration","policyOutcome":"Deny","rules":[]}

How can I resolve this.

**Comment by justin-fyfe** [comment]
This may be that the service has not started successfully and/or has not registered the proper MDM handler. I would ensure:

1. MDM handler for the `Patient` resource is in the `docker-compose.yml` file as: `SDB_MDM_RESOURCE=Patient`
2. That the MDM handler has successfully bound your handler (in the log file you will see an informational log message which reads: `Adding MDM listener for Patient`) - note you may have to increase log verbosity to `SDB_LOG_LEVEL=Informational`
3. On the [Jobs](https://help.santesuite.org/operations/cdr-administration/santedb-administration-panel/system-administration/jobs) screen a `Background matching for Patient` job has been registered
4. On the [Server Status Screen](https://help.santesuite.org/operations/cdr-administration/santedb-administration-panel/system-administration/server-status) screen for the `Realm` server under `Services` the following services are active and/or running:
<html>
<body>


Name|Status
-- | --
MDM Data Management ( Daemon) | Running
Basic MDM Freetext Search Service ( Passive) | Active
MDM Resource Merge Configuration ( Passive) | Active
MDM Record Matching Service ( Passive) | Active


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by brianraila** [comment]
Thanks @justin-fyfe .
I managed to get it working.
